# Generated by Django 5.1 on 2024-09-12 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nickname',
            field=models.CharField(default='Ник', max_length=100, verbose_name='Ник'),
        ),
    ]
