# Generated by Django 5.1 on 2024-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_user_avatar_alter_user_nickname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='image/avatars/def_avatar.jpg', upload_to='image/avatars', verbose_name='Аватар'),
        ),
    ]
