# Generated by Django 5.1 on 2024-09-21 16:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='Дата и время попытки отправки')),
                ('status', models.BooleanField(verbose_name='Статус попытки отправки')),
                ('server_response', models.CharField(blank=True, max_length=150, null=True, verbose_name='Ответ почтового сервера')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Попытка отправки сообщения',
                'verbose_name_plural': 'Попытки отправки сообщения',
            },
        ),
    ]
