# Generated by Django 5.1 on 2024-09-03 17:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='entry',
            name='date_of_entry',
            field=models.DateField(default=datetime.date(2024, 9, 3), help_text='Введите дату', verbose_name='Дата'),
        ),
    ]
