# Generated by Django 5.1 on 2024-09-03 17:18

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_entry_date_of_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='date_of_entry',
            field=models.DateField(default=django.utils.timezone.now, help_text='Введите дату', verbose_name='Дата'),
        ),
    ]
