# Generated by Django 5.1 on 2024-09-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_alter_entry_date_of_entry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entry',
            name='date_of_entry',
        ),
        migrations.AddField(
            model_name='entry',
            name='changed_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата изменения'),
        ),
        migrations.AddField(
            model_name='entry',
            name='published_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(help_text='Введите заголовок', max_length=255, verbose_name='Заголовок'),
        ),
    ]
