# Generated by Django 5.1 on 2024-09-15 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0004_remove_entry_date_of_entry_entry_changed_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='title',
            field=models.CharField(blank=True, help_text='Введите заголовок', max_length=255, null=True, verbose_name='Заголовок'),
        ),
    ]
